language: python
dist: xenial
sudo: true

python:
    - 3.8
install:
    - pip install -r requirements.txt codecov

script:
    - flake8
    - pytest projetomeu --cov=projetomeu
after_success:
    - codecov

